# SOPS Configuration for Nullspace Secrets Management
#
# This file configures SOPS to encrypt secrets files using Age encryption.
# Different environments use separate Age keys for isolation.
#
# Prerequisites:
#   brew install sops age  # macOS
#   apt install sops age   # Ubuntu/Debian
#
# Key generation:
#   age-keygen -o ~/.config/sops/age/keys.txt
#
# Usage:
#   sops secrets/staging/secrets.enc.yaml  # Edit encrypted file
#   sops -d secrets/staging/secrets.enc.yaml > .env  # Decrypt to stdout
#   sops -e secrets/staging/secrets.yaml > secrets/staging/secrets.enc.yaml  # Encrypt

creation_rules:
  # Production secrets - requires production key
  # Matches both source files (for encryption) and encrypted files (for decryption/editing)
  - path_regex: secrets/production/.*\.(yaml|json|env)$
    age: >-
      age1dx5k9k3jt8n7xvalqpn47gxfal4g2y56p864wwaetlhcx3z3v59sj9pvcl

  # Staging secrets - requires staging key
  - path_regex: secrets/staging/.*\.(yaml|json|env)$
    age: >-
      age1xaw2rdg74qg5qtxltsj9sjzul9uptelmuptge36xdz4d9x4r7q7qt6vn49

  # Development secrets - can use local development key
  - path_regex: secrets/development/.*\.(yaml|json|env)$
    age: >-
      age16xyaj827xfg0r8s76eg9r7uke6eknzcf4hnxgcmpdnq2qg7w0vlq3r3lqr

  # CI secrets - for GitHub Actions automated deployments
  - path_regex: secrets/ci/.*\.(yaml|json|env)$
    age: >-
      age1w7848h53gelq9arxpkjayaedvvjhwn6zvlesnsucstls5ej8k4gquj3f46

# Encrypted key suffixes
# Only these file patterns can be decrypted/encrypted with sops
encrypted_suffix: .enc.yaml
