import { GameState, GameType, PlayerStats } from '../../types';

export const INITIAL_CHIPS = 1000;
export const INITIAL_SHIELDS = 3;
export const INITIAL_DOUBLES = 3;

export const createInitialStats = (): PlayerStats => ({
  chips: INITIAL_CHIPS,
  shields: INITIAL_SHIELDS,
  doubles: INITIAL_DOUBLES,
  auraMeter: 0,
  rank: 1,
  history: [],
  pnlByGame: {},
  pnlHistory: [],
});

export const createInitialGameState = (): GameState => ({
  type: GameType.NONE,
  message: "TYPE '/' FOR FUN",
  bet: 50,
  stage: 'BETTING',
  playerCards: [],
  dealerCards: [],
  communityCards: [],
  dice: [],
  crapsPoint: null,
  crapsEpochPointEstablished: false,
  crapsMadePointsMask: 0,
  crapsBets: [],
  crapsUndoStack: [],
  crapsInputMode: 'NONE',
  crapsRollHistory: [],
  crapsEventLog: [],
  crapsLastRoundBets: [],
  crapsOddsCandidates: null,
  rouletteBets: [],
  rouletteUndoStack: [],
  rouletteLastRoundBets: [],
  rouletteHistory: [],
  rouletteInputMode: 'NONE',
  rouletteZeroRule: 'STANDARD',
  rouletteIsPrison: false,
  sicBoBets: [],
  sicBoHistory: [],
  sicBoInputMode: 'NONE',
  sicBoUndoStack: [],
  sicBoLastRoundBets: [],
  resolvedBets: [],
  resolvedBetsKey: 0,
  baccaratBets: [],
  baccaratUndoStack: [],
  baccaratLastRoundBets: [],
  baccaratPlayerTotal: null,
  baccaratBankerTotal: null,
  lastResult: 0,
  activeModifiers: { shield: false, double: false, super: false },
  baccaratSelection: 'PLAYER',
  insuranceBet: 0,
  blackjackStack: [],
  completedHands: [],
  blackjack21Plus3Bet: 0,
  blackjackPlayerValue: null,
  blackjackDealerValue: null,
  blackjackActions: {
    canHit: false,
    canStand: false,
    canDouble: false,
    canSplit: false,
  },
  threeCardPairPlusBet: 0,
  threeCardSixCardBonusBet: 0,
  threeCardProgressiveBet: 0,
  threeCardProgressiveJackpot: 10000,
  threeCardPlayerRank: null,
  threeCardDealerRank: null,
  threeCardDealerQualifies: null,
  uthTripsBet: 0,
  uthSixCardBonusBet: 0,
  uthProgressiveBet: 0,
  uthProgressiveJackpot: 10000,
  uthBonusCards: [],
  videoPokerHand: null,
  videoPokerMultiplier: null,
  casinoWarTieBet: 0,
  casinoWarOutcome: null,
  hiloAccumulator: 0,
  hiloGraphData: [],
  hiloRules: null,
  hiloNextMultipliers: null,
  sessionId: null,
  moveNumber: 0,
  sessionWager: 0,
  sessionInterimPayout: 0,
  superMode: null,
});
