{
 "title": "Chain",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Validator", "query": { "query": "label_values(deployer_name)" } },
   { "name": "Region", "query": { "query": "label_values(deployer_region)" } }
  ]
 },
 "panels": [
  {
   "title": "Mempool (Accounts)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "engine_application_mempool_accounts{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Mempool (Transactions)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "engine_application_mempool_transactions{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "TPS (Considered)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(engine_application_txs_considered_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "TPS (Finalized)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "irate(engine_application_txs_executed_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Current View",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "engine_consensus_voter_current_view{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Views per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 10 },
   "targets": [
    {
     "expr": "irate(engine_consensus_voter_current_view{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "View Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expression": "1/$A", "type": "math" }
   ]
  },
  {
   "title": "Marshal Height (Contiguous)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "engine_marshal_processed_height{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Certificate Height (Contiguous)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "engine_aggregator_certificates_processed{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Ancestry Latency (p75) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.75, rate(engine_application_ancestry_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Propose Latency (p75) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.75, rate(engine_application_propose_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Verify Latency (p75) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.75, rate(engine_application_verify_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Seeded Latency (p75) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.75, rate(engine_application_seeded_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Execute Latency (p75) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.75, rate(engine_application_execute_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Finalize Latency (p75) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.75, rate(engine_application_finalize_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Batch Size (p50)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "avg by(deployer_name, deployer_ip) (histogram_quantile(0.5, rate(engine_consensus_batcher_batch_size_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Batch Size (p90)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "avg by(deployer_name, deployer_ip) (histogram_quantile(0.9, rate(engine_consensus_batcher_batch_size_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Skipped Views",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "engine_consensus_voter_skipped_views_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Peers Blocked",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "expr": "network_tracker_blocked{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Batchable Messages Seen",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "irate(engine_consensus_batcher_added_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Batch Verifications",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 38 },
   "targets": [
    {
     "expr": "irate(engine_consensus_batcher_batch_size_count{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Batch Verify Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(engine_consensus_batcher_verify_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval]))",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Recover Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, rate(engine_consensus_voter_recover_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval]))",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Notarization Latency (p50) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.5, rate(engine_consensus_voter_notarization_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Notarization Latency (p90) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.9, rate(engine_consensus_voter_notarization_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Notarization Latency (p75)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.75, avg_over_time(engine_consensus_voter_notarization_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__interval])))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Notarization Latency (p99) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.99, rate(engine_consensus_voter_notarization_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Finalization Latency (p50) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.5, rate(engine_consensus_voter_finalization_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Finalization Latency (p95) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.95, rate(engine_consensus_voter_finalization_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Finalization Latency (p75)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.75, avg_over_time(engine_consensus_voter_finalization_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__interval])))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Finalization Latency (p99) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.99, rate(engine_consensus_voter_finalization_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "Resolver Active Fetches (Marshal)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "engine_marshal_resolver_fetch_active{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Resolver Active Fetches (Seeder)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 65 },
   "targets": [
    {
     "expr": "engine_seeder_resolver_fetch_active{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Resolver Active Fetches (Aggregator)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "engine_aggregator_resolver_fetch_active{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Buffer Waiters",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 65 },
   "targets": [
    {
     "expr": "engine_buffer_waiters{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "network_tracker_tracked{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 74 },
   "targets": [
    {
     "expr": "network_spawner_connections{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Dial Attempts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 74 },
   "targets": [
    {
     "expr": "sum by(deployer_name, deployer_ip) (network_dialer_attempts_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"})",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(runtime_inbound_bandwidth_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Outbound Bandwidth per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(runtime_outbound_bandwidth_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 83 },
   "targets": [
    {
     "expr": "sum by(deployer_name, deployer_ip) (runtime_tasks_running{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"})",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Freezer Resizes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "engine_marshal_finalized_blocks_freezer_resizes_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "Blocks: {{deployer_name}} ({{deployer_ip}})"
    },
    {
     "expr": "engine_marshal_finalizations_by_height_freezer_resizes_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "Finalized: {{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Disk Reads per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 92 },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Disk Writes per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 92 },
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Cached Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_Cached_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Prune Latency (p50) by Region",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(deployer_region) (histogram_quantile(0.5, rate(engine_application_prune_latency_bucket{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[$__rate_interval])))",
     "legendFormat": "{{deployer_region}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (deployer_name,deployer_ip) (1 - rate(node_cpu_seconds_total{mode=\"idle\", deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}[1m])) * 100",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Memory Usage (Virtual)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "runtime_process_virtual_memory{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "runtime_process_rss{deployer_name=~\"$Validator\", deployer_region=~\"$Region\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\", mountpoint=\"/\"} - node_filesystem_free_bytes{deployer_name=~\"$Validator\", deployer_region=~\"$Region\", mountpoint=\"/\"}",
     "legendFormat": "{{deployer_name}} ({{deployer_ip}})"
    }
   ]
  },
  {
   "title": "Node Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/binary.log\", deployer_name=~\"$Validator\", deployer_region=~\"$Region\"} | json | target !~ \".*nullspace_randotron.*\" | line_format ` [{{.detected_level}}] {{.fields_message}}`"
    }
   ]
  },
  {
   "title": "Randotron Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 126 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{filename=\"/var/log/binary.log\", deployer_name=~\"$Validator\", deployer_region=~\"$Region\"} | json | target =~ \".*nullspace_randotron.*\" | line_format ` [{{.detected_level}}] {{.fields_message}}{{if .fields_generating}} generating={{.fields_generating}}{{end}}{{if .fields_lobby}} lobby={{.fields_lobby}}{{end}}{{if .fields_battle}} battle={{.fields_battle}}{{end}}{{if .fields_elapsed}} elapsed={{.fields_elapsed}}{{end}}{{if .fields_attempts}} attempts={{.fields_attempts}}{{end}}`"
    }
   ]
  }
 ]
}